@echo off
REM ==========================================================================
REM System Information Gathering Script for Security Analysis
REM Author: Jacques Gariépy
REM Date: %DATE%
REM ==========================================================================
REM
REM                           *** IMPORTANT ***
REM
REM This script must be run as an administrator!
REM (Right-click -> Run as administrator)
REM
REM ==========================================================================
REM
REM                      *** EDUCATIONAL NOTE ***
REM
REM This script is intended for purely educational and demonstrative purposes.
REM It gathers detailed system information which can be sensitive.
REM It illustrates techniques used in system administration and security auditing.
REM Running this script is at the user's own risk. The user is responsible
REM for ensuring they have the necessary permissions and comply with all
REM applicable laws and policies, especially regarding data privacy and
REM system access, before running it or sharing its output. This script should
REM not be used without authorization or understanding its potential impact.
REM
REM ==========================================================================

REM -- Output File Configuration --
SET OutputFile="%USERPROFILE%\Desktop\Security_Report_%COMPUTERNAME%_%date:~-4,4%%date:~-7,2%%date:~-10,2%.txt"
echo Report generated by: %USERNAME% > %OutputFile%
echo Date and Time: %DATE% %TIME% >> %OutputFile%
echo Machine: %COMPUTERNAME% >> %OutputFile%
echo ================================================================ >> %OutputFile%
echo. >> %OutputFile%

echo [*** START OF INFORMATION GATHERING ***] >> %OutputFile%
echo. >> %OutputFile%

REM -- Basic Information --
echo [--- Section 1: User and Machine Information ---] >> %OutputFile%
echo Current Directory: %CD% >> %OutputFile%
echo User Domain: %USERDOMAIN% >> %OutputFile%
echo Logon Server: %LOGONSERVER% >> %OutputFile%
(whoami /all) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- System Information (OS, Hotfixes) --
echo [--- Section 2: System Information (OS, Hotfixes) ---] >> %OutputFile%
(systeminfo) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Hotfixes (WMIC QFE)] >> %OutputFile%
(wmic qfe list full /format:list) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Installed Software --
echo [--- Section 3: Installed Software (via MSI - potentially incomplete list) ---] >> %OutputFile%
(wmic product get Name, Version, Vendor, InstallDate) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Network Configuration --
echo [--- Section 4: Network Configuration ---] >> %OutputFile%
echo [IPCONFIG /ALL] >> %OutputFile%
(ipconfig /all) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [NETSTAT -ANOB (Open ports and associated processes)] >> %OutputFile%
(netstat -anob) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Windows Firewall Status] >> %OutputFile%
(netsh advfirewall show allprofiles) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Network Shares (NET SHARE)] >> %OutputFile%
(net share) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Processes and Services --
echo [--- Section 5: Processes and Services ---] >> %OutputFile%
echo [TASKLIST /SVC] >> %OutputFile%
(tasklist /svc) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Services (SC QUERY)] >> %OutputFile%
(sc query state= all) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Accounts and Local Security --
echo [--- Section 6: Accounts and Local Security ---] >> %OutputFile%
echo [Local User Accounts (NET USER)] >> %OutputFile%
(net user) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Local Administrators Group Members] >> %OutputFile%
(net localgroup administrators) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Password Policy (NET ACCOUNTS)] >> %OutputFile%
(net accounts) >> %OutputFile% 2>&1
echo. >> %OutputFile%
echo [Exporting Local Security Policy (to SecPol.cfg)] >> %OutputFile%
del SecPol.cfg > nul 2>&1
secedit /export /cfg SecPol.cfg /quiet
IF EXIST SecPol.cfg (type SecPol.cfg >> %OutputFile%) ELSE (echo Failed to export SecPol.cfg >> %OutputFile%)
echo. >> %OutputFile%

REM -- Scheduled Tasks --
echo [--- Section 7: Scheduled Tasks ---] >> %OutputFile%
(schtasks /query /fo LIST /v) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Environment Variables --
echo [--- Section 8: Environment Variables ---] >> %OutputFile%
(set) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Hardware Devices --
echo [--- Section 9: Hardware Devices ---] >> %OutputFile%
(wmic path Win32_PnPEntity get Caption, DeviceID) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Group Policies --
echo [--- Section 10: Group Policies ---] >> %OutputFile%
(gpresult /z) >> %OutputFile% 2>&1
echo. >> %OutputFile%

REM -- Installed Applications and Versions (Redundant with Section 3, but included as requested) --
echo [--- Section 11: Installed Applications and Versions ---] >> %OutputFile%
(wmic product get Name,Version) >> %OutputFile% 2>&1
echo. >> %OutputFile%

echo [*** END OF INFORMATION GATHERING ***] >> %OutputFile%
echo. >> %OutputFile%
echo ================================================================ >> %OutputFile%

echo.
echo The full report has been generated in:
echo %OutputFile%
echo The security policy export is in SecPol.cfg (if successful - check script directory).
echo.
echo Manual Analysis Required! This report is a baseline.
echo Finished.
pause
